# apiVersion: v1
# kind: Pod
# metadata:
#   name: store-app
#   labels:
#     component: store
# spec:
#   containers:
#     - name: store
#       image: szezecinski/store-app:v1
#       ports:
#         - containerPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 3
  selector:
    matchLabels:
      component: store
  template:
    metadata:
      labels:
        component: store
    spec:
      containers:
        - name: store
          image: szezecinski/store-app:v1
          ports:
            - containerPort: 80